#!/bin/bash
# Real Google OAuth Setup Script

echo "🔑 Setting Up Real Google OAuth Credentials"
echo "==========================================="

echo ""
echo "📋 Step-by-Step Guide:"
echo "======================"

echo ""
echo "1️⃣  CREATE GOOGLE CLOUD PROJECT"
echo "-------------------------------"
echo "• Open: https://console.cloud.google.com/"
echo "• Click 'Select a project' dropdown (top bar)"
echo "• Click 'New Project'"
echo "• Project name: 'GritDocs' (or similar)"
echo "• Click 'Create'"
echo "• Wait for project creation (30 seconds)"

echo ""
echo "2️⃣  ENABLE GOOGLE+ API"
echo "----------------------"
echo "• Go to: APIs & Services > Library"
echo "• Search: 'Google+ API'"
echo "• Click on 'Google+ API'"
echo "• Click 'Enable'"

echo ""
echo "3️⃣  CREATE OAUTH CONSENT SCREEN"
echo "-------------------------------"
echo "• Go to: APIs & Services > OAuth consent screen"
echo "• Choose: 'External' (for public use)"
echo "• Click 'Create'"
echo "• Fill required fields:"
echo "  - App name: 'GritDocs'"
echo "  - User support email: your-email@example.com"
echo "  - Developer contact: your-email@example.com"
echo "• Click 'Save and Continue'"
echo "• Skip Scopes page (click 'Save and Continue')"
echo "• Skip Test users page (click 'Save and Continue')"

echo ""
echo "4️⃣  CREATE OAUTH CREDENTIALS"
echo "----------------------------"
echo "• Go to: APIs & Services > Credentials"
echo "• Click 'Create Credentials'"
echo "• Choose 'OAuth 2.0 Client ID'"
echo "• Application type: 'Web application'"
echo "• Name: 'GritDocs Production'"

echo ""
echo "5️⃣  CONFIGURE AUTHORIZED URLS"
echo "-----------------------------"
echo "Add these EXACT URLs:"

echo ""
echo "Authorized JavaScript origins:"
echo "https://fopyamyrykwtlwgefxuq.supabase.co"

echo ""
echo "Authorized redirect URIs:"
echo "https://fopyamyrykwtlwgefxuq.supabase.co/auth/v1/callback"

echo ""
echo "• Click 'Create'"

echo ""
echo "6️⃣  COPY YOUR CREDENTIALS"
echo "------------------------"
echo "You'll get a popup with:"
echo "• Client ID: 123456789012-abc...xyz.apps.googleusercontent.com"
echo "• Client secret: GOCSPX-AbC...XyZ"
echo ""
echo "📝 COPY BOTH - you'll need them for Supabase!"

echo ""
echo "7️⃣  ADD TO SUPABASE"
echo "------------------"
echo "• Open: https://supabase.com/dashboard/project/fopyamyrykwtlwgefxuq/auth/providers"
echo "• Click 'Google'"
echo "• Paste Client ID"
echo "• Paste Client Secret"
echo "• Toggle 'Enable Google provider' ON"
echo "• Click 'Save'"

echo ""
echo "✅ EXPECTED RESULT"
echo "-----------------"
echo "• No more 'missing OAuth secret' error"
echo "• Google sign-in popup works"
echo "• Users can authenticate with Google"
echo "• Automatic profile creation"

echo ""
echo "🚀 Ready to proceed!"
echo ""
echo "Current steps:"
echo "1. Create Google Cloud project ← START HERE"
echo "2. Enable Google+ API"
echo "3. Set up OAuth consent screen"  
echo "4. Create OAuth credentials"
echo "5. Add credentials to Supabase"